rails:
  input:
    flows: 
      - self check input
# models:
#   - type: main
#     engine: huggingface_hub
#     model: Meta-Llama-3-8B-Instruct
#     parameters:
#         huggingfacehub_api_token: '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'
#         repo_id: meta-llama/Meta-Llama-3-8B-Instruct
#         # task: text2text-generation
#         model_kwargs: {token = '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'}
instructions:
  - type: general
    content: |
      
# models:
#  - type: main
#    engine: openai
#    model: gpt-3.5-turbo-instruct
#    parameters:
#        openai_api_key: 'sk-X822VaC_qofb5vCPEPh_OeYY5Ch7Pnt4q03eCGt498T3BlbkFJTc2DkWYpRrko3Cvh38VnjIxAVxc0MDlCIyDPjJ_G4A'